In [1]:
# Import necessary libraries
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [2]:
# Define sentences

sentences = [
     'the glass of milk', 
     'the glass of juice', 
     'the cup of tea', 
     'I am a good boy', 
     'I am a good developer', 
     'understand the meaning of words', 
     'your videos are good', 
     'how are you'
]

In [3]:
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good',
 'how are you']

In [4]:
vocabularySize = 10000

In [5]:
oneHotRepresentation = [one_hot(words, vocabularySize) for words in sentences]
print("One Hot Encoded Representation:", oneHotRepresentation)

One Hot Encoded Representation: [[4555, 5700, 8285, 7949], [4555, 5700, 8285, 3783], [4555, 2423, 8285, 1857], [3018, 8128, 8839, 1674, 7593], [3018, 8128, 8839, 1674, 8882], [9489, 4555, 8011, 8285, 2777], [449, 7056, 1150, 1674], [1652, 1150, 6749]]


In [6]:
sentenceLength = 8

embeddedDocuments = pad_sequences(
    oneHotRepresentation, 
    padding = 'pre', 
    maxlen = sentenceLength
)

print("Padded Sequences:", embeddedDocuments)

Padded Sequences: [[   0    0    0    0 4555 5700 8285 7949]
 [   0    0    0    0 4555 5700 8285 3783]
 [   0    0    0    0 4555 2423 8285 1857]
 [   0    0    0 3018 8128 8839 1674 7593]
 [   0    0    0 3018 8128 8839 1674 8882]
 [   0    0    0 9489 4555 8011 8285 2777]
 [   0    0    0    0  449 7056 1150 1674]
 [   0    0    0    0    0 1652 1150 6749]]


In [7]:
embeddingDimensions = 10

In [8]:
model = Sequential()
model.add(
    Embedding(
        vocabularySize, 
        embeddingDimensions, 
        input_length = sentenceLength
        )
    )

model.compile(
    optimizer='adam', 
    loss='mse'
)

/Users/keshavsaraogi/code/rnn/movies-rnn/tf-macos-env/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-02-15 19:32:02.497537: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2025-02-15 19:32:02.497566: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-02-15 19:32:02.497571: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2025-02-15 19:32:02.497589: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-02-15 19:32:02.497600: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, 

In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
embeddedDocuments[0]

array([   0,    0,    0,    0, 4555, 5700, 8285, 7949], dtype=int32)

In [11]:
# Predict using the trained model

prediction = model.predict(embeddedDocuments)

2025-02-15 19:32:02.670587: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


In [12]:
print("Predictions:", prediction)

Predictions: [[[ 1.1319708e-02 -4.1946255e-02  5.1148906e-03 -1.0562398e-02
   -4.1208901e-02 -4.3859687e-02  7.1978457e-03  4.9572680e-02
    3.8154829e-02  2.6508000e-02]
  [ 1.1319708e-02 -4.1946255e-02  5.1148906e-03 -1.0562398e-02
   -4.1208901e-02 -4.3859687e-02  7.1978457e-03  4.9572680e-02
    3.8154829e-02  2.6508000e-02]
  [ 1.1319708e-02 -4.1946255e-02  5.1148906e-03 -1.0562398e-02
   -4.1208901e-02 -4.3859687e-02  7.1978457e-03  4.9572680e-02
    3.8154829e-02  2.6508000e-02]
  [ 1.1319708e-02 -4.1946255e-02  5.1148906e-03 -1.0562398e-02
   -4.1208901e-02 -4.3859687e-02  7.1978457e-03  4.9572680e-02
    3.8154829e-02  2.6508000e-02]
  [ 4.1879799e-02 -6.1360113e-03  4.0982638e-02 -1.7715834e-02
   -3.4400381e-02 -1.1464465e-02 -3.4655798e-02  3.9976347e-02
    3.6352504e-02  4.2302981e-03]
  [ 4.6680953e-02  4.5958605e-02 -1.4317609e-02  7.4266419e-03
    2.1642078e-02  4.5579102e-02 -3.1694971e-02  3.1740632e-02
    4.5214605e-02  4.7487233e-02]
  [-3.3751018e-03  1.747543